export { default as loginBanner } from './src/assets/images/loginBanner.png'
export { default as eyeOpen } from './src/assets/images/eyeOpen.svg'
export { default as eyeClose } from './src/assets/images/eyeClose.svg'
export { default as logo } from './src/assets/images/logo.svg'
export { default as shoppingBag } from '/src/assets/images/shoppingBag.svg'
export { default as profile } from '/src/assets/images/Profile.svg'
export { default as orderIcon } from '/src/assets/images/orderIcon.svg'
export {default as logoutIcon} from '/src/assets/images/logoutIcon.svg'
export {default as monthlyBillIcon} from '/src/assets/images/monthlyBillIcon.svg'
export {default as monthlyInsuranceBill} from '/src/assets/images/monthlyInsuranceBill.svg'
export {default as arrowRight} from '/src/assets/images/arrowRight.svg'
export { default as collectionImg} from '/src/assets/images/collectionImg.png'